package types;

import java.util.List;



public class BullsAndCows extends AbstractMastermindGame {
	
	

	public BullsAndCows(int seed, int size, Colour[] colours) {
		super(seed, size, colours);
		// TODO Auto-generated constructor stub
		}
		
	@Override
	public boolean isRoundFinished() {
		// TODO Auto-generated method stub
		if (wasSecretRevealed() || getNumberOfTrials() >= MAX_TRIALS) {
			return true;
		}
		
		return false;
	}

	@Override
	public int score() {
		return currentScore;
	}

	@Override
	public boolean updateScore() {
        currentScore += 2000;
        return true;}
	
	//FALTA COLOUR HINT REIMPLEMENRZ
	@Override
    public Colour hint() {
		Colour newHint = super.hint();  // Call the parent method to get the hint
		this.currentScore /= 2;  // Increment the number of hints
        return newHint;  // Return the same hint generated by the parent method
    }
}
