package types;

import java.util.List;



public class MultiColourMastermindGame extends AbstractMastermindGame{
	
	protected int numberOfHints; // Stores the current number of Hints

	public MultiColourMastermindGame(int seed, int size, Colour[] colours) {
		super(seed, size, colours);
	}

	@Override
	public int score() {
		return currentScore;
	}

	@Override
	public boolean isRoundFinished() {
		if (wasSecretRevealed() || MAX_TRIALS == getNumberOfTrials()) {
			return true;
		}
		
		return false;
	}

	@Override
    public boolean updateScore() {
        if (getNumberOfTrials() <= 2) {
            currentScore += 1000 / (numberOfHints + 1); }
        else if (getNumberOfTrials() <= 5) {
            currentScore += 50 / (numberOfHints + 1); }
        else {
            currentScore += 20 / (numberOfHints + 1); }
        return true;
    }
	
	@Override
    public Colour hint() {
		Colour newHint = super.hint();  // Call the parent method to get the hint
		this.numberOfHints += 1;  // Increment the number of hints
        return newHint;  // Return the same hint generated by the parent method
    }

}
