package games;

import java.util.List;

import types.Colour;

public class BullsAndCows extends AbstractMastermindGame {
	
	

	public BullsAndCows(int seed, int size, Colour[] colours) {
		super(seed, size, colours);
		// TODO Auto-generated constructor stub
		}
		
	@Override
	public boolean isRoundFinished() {
		// TODO Auto-generated method stub
		if (wasSecretRevealed() || MAX_TRIALS == getNumberOfTrials()) {
			return true;
		}
		
		return false;
	}

	@Override
	public int score() {
		return currentScore;
	}

	@Override
	public boolean updateScore() {
		this.currentScore += 3;//isto é só teste :P para a minha funcao funcionar, n funciona como o stor disse
		return false;
	}
	
	//FALTA COLOUR HINT REIMPLEMENRZ
	@Override
    public Colour hint() {
		Colour newHint = super.hint();  // Call the parent method to get the hint
		this.currentScore /= 2;  // Increment the number of hints
        return newHint;  // Return the same hint generated by the parent method
    }
}
