package games;

import java.util.List;

import types.Colour;

public class MultiColourMastermindGame extends AbstractMastermindGame{
	
	protected int numberOfHints; // Stores the current number of Hints

	public MultiColourMastermindGame(int seed, int size, Colour[] colours) {
		super(seed, size, colours);
	}

	@Override
	public int score() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public boolean isRoundFinished() {
		if (wasSecretRevealed() || MAX_TRIALS == getNumberOfTrials()) {
			return true;
		}
		
		return false;
	}

	@Override
	public boolean updateScore() {
		this.currentScore += 3;//isto é só teste :P para a minha funcao funcionar, n funciona como o stor disse
		return false;
	}
	
	@Override
    public Colour hint() {
		Colour newHint = super.hint();  // Call the parent method to get the hint
		this.numberOfHints += 1;  // Increment the number of hints
        return newHint;  // Return the same hint generated by the parent method
    }

}
